// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMxzuHDPdElDxevd3BsuYMedmI6v0kM2s',
    appId: '1:132014883979:web:c719d0745f51686eb6408e',
    messagingSenderId: '132014883979',
    projectId: 'tvalgo2026',
    authDomain: 'tvalgo2026.firebaseapp.com',
    storageBucket: 'tvalgo2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmixSrOgVhuWg2FIwygp0EkUFV7tdDMAM',
    appId: '1:132014883979:android:5e7e9201d24a56c0b6408e',
    messagingSenderId: '132014883979',
    projectId: 'tvalgo2026',
    storageBucket: 'tvalgo2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCS0L5Knm2hR1_CX4zzELiBbfhGytPy7A',
    appId: '1:132014883979:ios:5640b865dc17773eb6408e',
    messagingSenderId: '132014883979',
    projectId: 'tvalgo2026',
    storageBucket: 'tvalgo2026.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCS0L5Knm2hR1_CX4zzELiBbfhGytPy7A',
    appId: '1:132014883979:ios:5640b865dc17773eb6408e',
    messagingSenderId: '132014883979',
    projectId: 'tvalgo2026',
    storageBucket: 'tvalgo2026.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMxzuHDPdElDxevd3BsuYMedmI6v0kM2s',
    appId: '1:132014883979:web:797e30b57e65e4f0b6408e',
    messagingSenderId: '132014883979',
    projectId: 'tvalgo2026',
    authDomain: 'tvalgo2026.firebaseapp.com',
    storageBucket: 'tvalgo2026.firebasestorage.app',
  );
}
